import { getCurrentOutputs } from "@/lib/api";

export default async function OutputsPage() {
    const data = await getCurrentOutputs();

    return (
        <main className="min-h-screen bg-slate-950 p-8 text-white">
            <a href="/" className="text-blue-400">
                Back to Dashboard
            </a>

            <h1 className="mt-6 text-4xl font-bold">Output Files</h1>

            <p className="mt-2 text-gray-400">
                Current CrewAI output files generated by your 8 agents.
            </p>

            <div className="mt-8 rounded-xl border border-white/10 bg-white/5 p-5">
                <p className="text-sm text-gray-400">Total Files</p>
                <h2 className="mt-2 text-3xl font-bold">{data.count}</h2>
            </div>

            <div className="mt-8 grid gap-4">
                {data.files?.map((file: any) => (
                    <div
                        key={file.name}
                        className="rounded-xl border border-white/10 bg-white/5 p-5"
                    >
                        <h2 className="text-xl font-semibold">{file.name}</h2>

                        <p className="mt-3 text-sm text-gray-400">Path</p>
                        <p className="mt-1 break-all text-gray-200">{file.path}</p>

                        <p className="mt-3 text-sm text-gray-400">Size</p>
                        <p className="mt-1 text-gray-200">{file.size} bytes</p>
                    </div>
                ))}
            </div>
        </main>
    );
}
